language: node_js

node_js:
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'
  - 'node'
  - 'lts/*'
script:
  - npm run ci
jobs:
  include:
    - stage: Tests
      name: Code Coverage
      script: npm run ci
    - name: Unit Tests
      script: npm run test
    - name: Test Build
      script: npm run compile
